spring:
  datasource:
    username: admin
    password: 123
    url: jdbc:postgresql://localhost:5433/smart_budget
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:liquibase/liquibase.yaml