version: '3.8'

services:
  db:
    image: postgres:12.3
    environment:
      POSTGRES_DB: smart_budget
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
    ports:
      - "5433:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql